version: "3.7"

services:
  pricebot:
    image: znibb/pricebot:latest
    container_name: pricebot
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - pricebot
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  pricebot:
    name: pricebot
    driver: bridge
